/**
 * Arabic (default) interface strings for the admin chrome. Product/business
 * content is bilingual and comes from the API; this covers the UI shell only.
 * Kept in one place so a French locale can be layered on later.
 */
export const strings = {
  appName: 'دارار',
  appSubtitle: 'لوحة الإدارة',
  common: {
    loading: 'جارٍ التحميل...',
    logout: 'تسجيل الخروج',
    search: 'بحث',
    comingSoon: 'قريباً',
    account: 'الحساب',
    save: 'حفظ',
    saving: 'جارٍ الحفظ...',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    add: 'إضافة',
    create: 'إنشاء',
    actions: 'إجراءات',
    all: 'الكل',
    active: 'مفعّل',
    inactive: 'غير مفعّل',
    yes: 'نعم',
    no: 'لا',
    showing: 'عرض',
    of: 'من',
    noResults: 'لا توجد نتائج',
    required: 'هذا الحقل مطلوب',
    confirmDelete: 'تأكيد الحذف',
    saved: 'تم الحفظ بنجاح',
    deleted: 'تم الحذف بنجاح',
    back: 'رجوع',
  },
  catalog: {
    categories: {
      title: 'التصنيفات',
      add: 'تصنيف جديد',
      edit: 'تعديل التصنيف',
      nameAr: 'الاسم (عربي)',
      nameFr: 'الاسم (فرنسي)',
      descAr: 'الوصف (عربي)',
      descFr: 'الوصف (فرنسي)',
      parent: 'التصنيف الأب',
      noParent: 'بدون (تصنيف رئيسي)',
      sortOrder: 'الترتيب',
      products: 'المنتجات',
      subcategories: 'التصنيفات الفرعية',
      slug: 'المُعرّف (slug)',
      empty: 'لا توجد تصنيفات بعد',
      deleteMessage: 'هل أنت متأكد من حذف هذا التصنيف؟',
    },
    products: {
      title: 'المنتجات',
      add: 'منتج جديد',
      create: 'إضافة منتج',
      edit: 'تعديل المنتج',
      arabicSection: '🇹🇳 المحتوى بالعربية',
      frenchSection: '🇫🇷 المحتوى بالفرنسية',
      basicInfo: 'معلومات أساسية',
      pricing: 'التسعير',
      organization: 'التصنيف والحالة',
      images: 'الصور',
      name: 'اسم المنتج',
      shortDesc: 'وصف قصير',
      fullDesc: 'الوصف الكامل',
      sku: 'رمز المنتج (SKU)',
      price: 'السعر',
      oldPrice: 'السعر القديم',
      category: 'التصنيف',
      noCategory: 'بدون تصنيف',
      status: 'الحالة',
      featured: 'منتج مميّز',
      product: 'المنتج',
      allStatuses: 'كل الحالات',
      allCategories: 'كل التصنيفات',
      empty: 'لا توجد منتجات',
      deleteMessage: 'هل أنت متأكد من حذف هذا المنتج؟',
      uploadImages: 'رفع صور',
      setPrimary: 'تعيين كصورة رئيسية',
      primary: 'رئيسية',
      dropHint: 'اختر صور المنتج (JPG، PNG، WebP)',
      searchPlaceholder: 'ابحث بالاسم أو رمز المنتج...',
    },
    status: {
      DRAFT: 'مسودة',
      ACTIVE: 'مفعّل',
      INACTIVE: 'غير مفعّل',
      ARCHIVED: 'مؤرشف',
    },
  },
  commerce: {
    customers: {
      title: 'العملاء',
      add: 'عميل جديد',
      edit: 'تعديل العميل',
      detail: 'تفاصيل العميل',
      firstName: 'الاسم',
      lastName: 'اللقب',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      orders: 'الطلبات',
      totalSpent: 'إجمالي الإنفاق',
      recentOrders: 'أحدث الطلبات',
      empty: 'لا يوجد عملاء',
      noOrders: 'لا توجد طلبات',
      deleteMessage: 'هل أنت متأكد من حذف هذا العميل؟',
      searchPlaceholder: 'ابحث بالاسم أو البريد أو الهاتف...',
    },
    orders: {
      title: 'الطلبات',
      create: 'طلب جديد',
      detail: 'تفاصيل الطلب',
      orderNumber: 'رقم الطلب',
      customer: 'العميل',
      guestCustomer: 'عميل غير مسجّل',
      date: 'التاريخ',
      status: 'الحالة',
      paymentStatus: 'حالة الدفع',
      paymentMethod: 'طريقة الدفع',
      items: 'المنتجات',
      item: 'المنتج',
      quantity: 'الكمية',
      unitPrice: 'سعر الوحدة',
      lineTotal: 'المجموع',
      subtotal: 'المجموع الفرعي',
      discount: 'الخصم',
      shipping: 'التوصيل',
      total: 'الإجمالي',
      shippingAddress: 'عنوان التوصيل',
      notes: 'ملاحظات',
      empty: 'لا توجد طلبات',
      allStatuses: 'كل الحالات',
      allPayments: 'كل حالات الدفع',
      addItem: 'إضافة منتج',
      selectProduct: 'اختر منتجاً',
      selectCustomer: 'اختر عميلاً',
      noItems: 'أضف منتجاً واحداً على الأقل',
      updateStatus: 'تحديث الحالة',
      searchPlaceholder: 'ابحث برقم الطلب أو اسم العميل...',
    },
    orderStatus: {
      PENDING: 'قيد الانتظار',
      CONFIRMED: 'مؤكّد',
      PROCESSING: 'قيد التجهيز',
      SHIPPED: 'تم الشحن',
      DELIVERED: 'تم التسليم',
      CANCELLED: 'ملغى',
    },
    paymentStatus: {
      PENDING: 'قيد الانتظار',
      PAID: 'مدفوع',
      FAILED: 'فشل',
      REFUNDED: 'مُسترجع',
    },
  },
  login: {
    title: 'تسجيل الدخول',
    subtitle: 'أدخل بياناتك للوصول إلى لوحة الإدارة',
    email: 'البريد الإلكتروني',
    emailPlaceholder: 'admin@darihome.tn',
    password: 'كلمة المرور',
    passwordPlaceholder: '••••••••',
    submit: 'دخول',
    submitting: 'جارٍ الدخول...',
    invalidEmail: 'يرجى إدخال بريد إلكتروني صحيح',
    passwordRequired: 'يرجى إدخال كلمة المرور',
    failed: 'فشل تسجيل الدخول',
  },
  dashboard: {
    title: 'لوحة التحكم',
    welcome: 'نظرة عامة على أداء متجرك',
    periods: {
      all: 'الكل',
      year: 'سنة',
      month: 'شهر',
      week: 'أسبوع',
      day: 'يوم',
    },
    kpiOrders: 'الطلبات',
    kpiPending: 'قيد الانتظار',
    kpiRevenue: 'الإيرادات',
    kpiRevenueHint: 'من الطلبات المُسلَّمة',
    kpiNewCustomers: 'عملاء جدد',
    kpiActiveProducts: 'منتجات نشطة',
    ordersByStatus: 'الطلبات حسب الحالة',
    recentOrders: 'أحدث الطلبات',
    revenueTrend: 'تطوّر الإيرادات',
    viewAllOrders: 'عرض الكل',
    noOrders: 'لا توجد طلبات بعد',
    noData: 'لا توجد بيانات لعرضها',
  },
  settings: {
    title: 'الإعدادات',
    delivery: 'التوصيل',
    deliveryDesc: 'سعر التوصيل الثابت وحدّ التوصيل المجاني الذي يراه العملاء عند الطلب.',
    fee: 'سعر التوصيل',
    feeHint: 'يُطبَّق على كل طلب (بالدينار).',
    threshold: 'حدّ التوصيل المجاني',
    thresholdHint: 'عند بلوغ هذا المجموع يصبح التوصيل مجانيًا. اكتب 0 لتعطيله.',
    save: 'حفظ التغييرات',
    saved: 'تم حفظ الإعدادات',
    invalid: 'يرجى إدخال أرقام صحيحة غير سالبة.',
  },
  nav: {
    dashboard: 'لوحة التحكم',
    products: 'المنتجات',
    categories: 'التصنيفات',
    orders: 'الطلبات',
    customers: 'العملاء',
    users: 'المستخدمون',
    settings: 'الإعدادات',
  },
} as const;
